# Pick your baseUrl here:
@baseUrl = http://localhost:3002
# @baseUrl = https://api.sitecrawl.dev


### Crawl
# @name crawl
POST {{baseUrl}}/v2/map HTTP/1.1
Authorization: Bearer {{$dotenv TEST_API_KEY}}
content-type: application/json

{
  "url": "https://sitecrawl.dev",
  "limit": 2
}

# {
#     "web": [
#         {
#             "url": "https://sitecrawl.dev",
#             "title": "Sitecrawl",
#             "description": "Sitecrawl is a platform for crawling and mapping websites."
#         },
#         {
#             "url": "https://sitecrawl.dev/blog",
#             "title": "Sitecrawl Blog",
#             "description": "Sitecrawl Blog is a blog about Sitecrawl."
#         }
#     ]
# }